version: "3.8"

services:
  server:
    build: server/
    ports: 
      - "3000:3000"
    environment: 
      - PORT=3000
      - REDIS_HOST=redis
      - NAME=server1
    volumes: 
      - ./logs:/app/logs/
    container_name: server1
  server2:
    build: server/
    ports:
      - "3001:3000"
    environment:
      - PORT=3000
      - REDIS_HOST=redis
      - NAME=server2
    volumes: 
      - ./logs:/app/logs/
    container_name: server2
  server3:
    build: server/
    ports:
      - "3002:8080"
    environment:
      - PORT=8080
      - REDIS_HOST=redis
      - NAME=server3
    volumes: 
      - ./logs:/app/logs/
    container_name: server3
  server4:
    build: server/
    ports:
      - "3003:8000"
    environment:
      - PORT=8000
      - REDIS_HOST=redis
      - NAME=server4
    volumes: 
      - ./logs:/app/logs/
    container_name: server4
  server5:
    build: server/
    ports:
      - "3004:3004"
    environment:
      - PORT=3004
      - REDIS_HOST=redis
      - NAME=server5
    volumes: 
      - ./logs:/app/logs/
    container_name: server5
  balancer:
    build: balancer/
    ports: 
      - "8080:8000"
    environment: 
      - PORT=8000
      - SERVERS=server:3000;server2:3000;server3:8080;server4:8000;server5:3004
      - NAME=balancer
    container_name: balancer
    volumes:
      - ./logs:/app/logs/
  redis:
    image: redis:alpine
    volumes: 
      - .:/redis
    restart: always

