version: "3.8"

services:
  server:
    build: server/
    ports: 
      - "3000:3000"
    environment: 
      - PORT=3000
    container_name: server1
  server2:
    build: server/
    ports:
      - "3001:3000"
    environment:
      - PORT=3000
    container_name: server2
  balancer:
    build: balancer/
    ports: 
      - "8080:8000"
    environment: 
      - PORT=8000
      - SERVERS=server:3000;server2:3000
    container_name: balancer

